permalink: pretty
sass: 
  style: compressed

optional_front_matter:
  remove_originals: true
  
readme_index:
  remove_originals: true
  
plugins:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-include-cache
